### ISSUE TITLE
sbt dependency error

### ISSUE THREAD

**Issue by gaocegege** [codacy/sbt-codacy-coverage#10]
Hi, today I want to get the coverage report from the codacy, but I got this:
`sbt.ResolveException: unresolved dependency: org.scoverage#sbt-scoverage;1.3.1: not found`

Is there something wrong?

**Comment by pedrorijo91** [comment]
As far as I see, the latest version is 1.1.1 

http://mvnrepository.com/artifact/org.scoverage/scalac-scoverage-plugin_2.11

**Comment by gaocegege** [comment]
enh, so the setup section in the readme.md is wrong~?

**Comment by pedrorijo91** [comment]
sorry, my mistake. I was looking into Scoverage Scala Code Coverage Core Libs  https://github.com/scoverage/scalac-scoverage-plugin

This project uses version `1.3.3` and it works: https://github.com/codacy/codacy-coverage-reporter/blob/master/project/plugins.sbt

But with version `1.3.1` I get the same error. Try with `1.3.3` for now please. I will find why are we getting this error

**Comment by pedrorijo91** [comment]
It looks like `1.3.1` has been deleted: https://repo1.maven.org/maven2/org/scoverage/sbt-scoverage_2.10_0.13/

Going to update the documentation

**Comment by gaocegege** [comment]
😄ok~

**Comment by pedrorijo91** [comment]
Worked for you? Gonna close this issue then.

Thanks for the report !

**Comment by gaocegege** [comment]
yeah, LGTM
