### ISSUE TITLE
Scala 2.11

### ISSUE THREAD

**Issue by ankitcha** [codacy/sbt-codacy-coverage#13]
Hi,

Is there a plan to release this plugin for scala 2.11?

**Comment by machadoit** [comment]
Hi,

Are you having any problem?
We use 2.10 everywhere and we have no problem whatsoever.

**Comment by ankitcha** [comment]
I am sorry...I was not able to pull this plugin in sbt due to some error on our internal repo configuration. 

I thought that it was because of version mismatch but forget that sbt 0.13 is compiled with scala 2.10

Anyways, after fixing our repo configurations, its working so closing this out.

Thanks for the quick response!
