### ISSUE TITLE
Codacy not publishing any coverage results

### ISSUE THREAD

**Issue by newhoggy** [codacy/sbt-codacy-coverage#21]
See: https://circleci.com/gh/pico-works/pico-unsigned/5 and https://github.com/pico-works/pico-unsigned

I'm wondering if it has anything to do with cross compiling with Scala `2.10.x` and `2.11.x`

**Comment by newhoggy** [comment]
And https://www.codacy.com/app/newhoggy/pico-works-pico-unsigned/dashboard

**Comment by pedrorijo91** [comment]
Hi @newhoggy 

Sorry for took some time to answer to your question. As far as I can see, you already have coverage displayed on your codacy dashboard, so I assume it is solved?

The coverage is only displayed after the referred commit to be analysed, and it may have been the cause of the delay you observed.

In the future, for questions regarding Codacy itself (and not our OSS tools), ping us on our platform support chat for faster answers.
