### ISSUE TITLE
codacyCoverage task fails on shippable when build PR from fork

### ISSUE THREAD

**Issue by kpmeen** [codacy/sbt-codacy-coverage#30]
When using a cloud CI system like Shippable where the codacy project token is encrypted, the following line causes issues with builds of PR's from forks.

https://github.com/codacy/sbt-codacy-coverage/blob/master/src/main/scala/com/codacy/CodacyCoveragePlugin.scala#L69 (introduced in commit ed61a32328ede2941ab25ec537d7a68945df2080)

Versions of the sbt-codacy-coverage plugin prior to the introduction of the above line, would just log that the coverage report could not be pushed.

All versions after this line was introduced, will _fail_ the builds of PR's from forks. The reason being that these builds will not have access to a decrypted version of the token. Which is not good.

Ideally it should be configurable whether or not the task should fail if it cannot push.

**Comment by pedrorijo91** [comment]
Hi @kpmeen,

We don't have experience with Shippable, but other CI systems typically allow to set environment variables. Even private/secret environment variables are accessible on runtime, and the sbt plugin can use the project token as an environment variable.

Doesn't that happen on Shippable?

**Comment by kpmeen** [comment]
Hi @pedrorijo91,

Shippable is very similar to e.g. Travis CI. In fact, the Shippable can handle Travis CI configs just as well as their own format.

As mentioned above, this error only occurs when building a PR that was created from a fork of the upstream repository. Because, on Shippable, encrypted tokens are only available to branches from the upstream repository.

I found a workaround for the problem though (see below). But, IMO it is not correct to exit with 0 if the build isn't able to push the coverage results to Codacy. In many cases it is a "nice to have" feature, but not something that would/should stop the build pipeline.

Workaround for shippable:

```
// omitted stuff
...
build:
  ci:
    - sbt clean coverage test coverageReport
    - sbt coverageAggregate
    - if [[ -n "$CODACY_PROJECT_TOKEN" ]]; then sbt codacyCoverage; else echo "Coverage reporting disabled for PR from forks"; fi

...
```

I can live with this workaround. But if others stumble upon the same issue it should be documented somewhere.

**Comment by pedrorijo91** [comment]
Thanks for the clarification! I now understand your problem.

While it can be a nice to have feature, just as you said, we do not have the time to develop it currently, but if you find the time to do it, and create a PR, we will certainly have a look at it so that it can be merged quickly.

**Comment by rtfpessoa** [comment]
Added note in #39
