### ISSUE TITLE
Incorrect overall coverage reporting

### ISSUE THREAD

**Issue by VladUreche** [codacy/sbt-codacy-coverage#4]
I use `sbt-scoverage` to obtain coverage information in a multi-project setting and when I upload the data to codacy, I have two possible ways to do it:
- for the aggregate project, after running `coverageAggregate` => I see individual file coverage, but the overall coverage is incorrectly shown as `100%`
- for the one sub-project I care about => I see the correct overall coverage, but not individual file coverage

The workaround is to publish both: https://github.com/miniboxing/miniboxing-plugin/commit/5cec36143bd49f33a3fdab2c8010d842bd29c882#diff-354f30a63fb0907d4ad57269548329e3R3, which codacy conveniently combines into the correct information. 

Still, it would be great if `codacyCoverage` would correctly transfer both the overall coverage and the individual coverage for each file. My guess is that `codacyCoverage` reports data for each subproject separately, and each time overrides the previous overall coverage. This way, what is shown in the end is the overall coverage for the last reported subproject, which, in my case is not instrumented at all, resulting in a fake 100% coverage for the entire project.

**Comment by pedrorijo91** [comment]
@mrfyda is this to be fixed? or won't fix?

**Comment by rtfpessoa** [comment]
This might get addressed in the future inside the product but not in this specific plugin.
