### ISSUE TITLE
Codacy is unable to locate files when generating a report using sbt-scoverage 1.1.0

### ISSUE THREAD

**Issue by bfil** [codacy/sbt-codacy-coverage#6]
Codacy shows "No Coverage data" when using sbt-scoverage `1.1.0` because of a change in the generated file paths in the reports (https://github.com/scoverage/sbt-scoverage/issues/69)

Codacy support stated that the path generated by sbt-scoverage `1.1.0` are not recognized as valid, here's an example of the new paths that are generated:

`com/example/package/SomeClass.scala`

While Codacy it's expecting to locate the files using the following path:

`src/main/scala/com/example/package/SomeClass.scala`

**Comment by mrfyda** [comment]
Hi @bfil 

This is now fixed since version 1.2.1.
